<?php /** @var \App\Entity\Patient $item */
foreach ($this->items as $item): ?>
    <?php $address_edit=$this->url('patient.edit', ['id'=>$item->getPatientId()]); ?>

    <tr data-id="<?=$item->getPatientId(); ?>" >
        <td>
            <div class="img-thumbnail photo-small">
                <a href="<?= $address_edit ?>">
                    <?php if ($item->getImage()): ?>
                        <img
                                src="data:image;base64,<?= base64_encode(stream_get_contents($item->getImage())); ?>"
                                style="height: 60px;">
                    <?php else: ?>
                        <img src="/img/first.png" style="width: 100%">
                    <?php endif; ?>
                </a>
            </div>
        </td>
        <td>
<!--            <a href="--><?//= $address_edit ?><!--">-->
                <?=$this->escapeHtml($item->getFirstName())?><br>
                <?=$this->escapeHtml($item->getSurname())?>
<!--            </a>-->
        </td>
        <td>
            <?= $item->getBirthday()?$item->getBirthday()->format('d-m-Y'):''; ?>
        </td>
        <td>
            <a class="btn btn-info pull-left" href="<?= $address_edit ?>">
                <i class="fa fa-pencil" aria-hidden="true"></i> Ansehen
                <br><span class="english-label">view</span>
            </a>
        </td>
    </tr>

<?php endforeach; ?>
