<?php
/** @var \Laminas\View\Renderer\PhpRenderer $this */
$this->headTitle('Patients list');
$keyword=$this->keyword;
$this->inlineScript()
    ->prependFile('/js/patients.js');

?>
<div class="h3">Patienten</div>
<hr>

<form id="search-patients" autocomplete="off">
    <div class="form-group position-relative has-clear input-group">
        <input id="filter-keyword" type="text" name="keyword"
               class="form-control "
               placeholder="nachname oder vorname des patienten"
               value="<?= $this->escapeHtml($keyword); ?>" >
        <i class="far fa-times-circle form-control-clear invisible"></i>
        <div class="input-group-append">
            <button type="submit" class="btn  btn-primary">
                <i class="fas fa-search" aria-hidden="true"></i><?=$this->lngLabel('Finden', 'find')?>
            </button>
        </div>
    </div>
</form>

<form method="post" action="<?= $this->url('patient.create'); ?>">
    <button type="submit" class="btn btn-sm btn-success mt-3">
        <i class="fa fa-plus" aria-hidden="true"></i><?=$this->lngButton('Schaffen', 'create')?>
    </button>
</form>

<div class="table-responsive">
    <table class="table table-hover">
        <thead class="thead-dark">
            <tr>
                <th scope="col"><?=$this->lngLabel('Patient', 'patient', true)?></th>
                <th scope="col"><?=$this->lngLabel('Geburtsdatum', 'birthday', true)?></th>
                <th scope="col"><?=$this->lngLabel('Betrieb', 'operations', true)?></th>
            </tr>
        </thead>
        <tbody></tbody>

    </table>
</div>

<div id="img-load" class="text-center" style="display: none">
    <img src="/img/ajax-loader.gif" alt="loading">
</div>
<div class="text-center" style="display:none">
    <button id="more" class="btn btn-primary">More...</button><br /><br />
</div>

