<?php
/** @var \App\Entity\Operation $operation */
$operation = $this->operation;
$identity = $this->identity;
if (!$operation) {
    return;
}
$labels = [
    'date'          => $this->lngLabel('Datum', 'date'),
    'remarks'       => $this->lngLabel('Bemerkungen', 'remarks'),
    'caseNumber'    => $this->lngLabel('Fallnummer', 'case number'),
    'patientHeight' => $this->lngLabel('Patientengröße', 'patient height'),
    'patientWeight' => $this->lngLabel('Patientengewicht', 'patient weight'),
    'surgeon'       => $this->lngLabel('Operateur', 'surgeon'),
    'clinic'        => $this->lngLabel('Klinik', 'clinic'),
    'kind'          => $this->lngLabel('Typ', 'type'),
];

$date_text = $operation->getDate() ? $operation->getDate()->format('d-m-Y H:i') : '...';
$date_value = $operation->getDate() ? $operation->getDate()->format('d-m-Y H:i') : '';
$remove_text1a = 'Löschen operation ';
$remove_text2a = 'delete operation ';
$remove_text1 = $remove_text1a . $date_text;
$remove_text2 = $remove_text2a . $date_text;

$id = $operation->getOperationId();

?>


<tr data-id="<?=$id?>" class="operation-row delete-object">
    <input type="hidden"
           class="form-control form-control-sm"
           name="operation[<?=$id?>][surgeonId]"
           id="operation[<?=$id?>][surgeonId]"
           value="<?=$operation->getSurgeon() ? $operation->getSurgeon()->getSurgeonId() : null?>"
    >
    <input type="hidden"
           class="form-control form-control-sm"
           name="operation[<?=$id?>][operationId]"
           id="operation[<?=$id?>][operationId]"
           value="<?=$id?>"
    >
    <input type="hidden"
           class="form-control form-control-sm"
           name="operation[<?=$id?>][clinicId]"
           id="operation[<?=$id?>][clinicId]"
           value="<?=$operation->getClinic() ? $operation->getClinic()->getClinicId() : null?>"
    >
    <td>
        <div class="row">
            <div class="col-6">
                <div class="h5">
                    <?=$this->lngLabel('Betrieb', 'operation')?>
                    <span class="badge badge-primary"><?=$this->object_num?></span>
                </div>
            </div>
            <div class="col-6">
                <a href="javascript:void(0)"
                   onclick="removeDocument('<?=$this->url('operation.delete',['id'=>$id])?>', '<?=$remove_text1?>', '<?=$remove_text2?>', this)"
                   class="btn btn-sm btn-danger">
                    <i class="fas fa-trash"></i> <?=$this->lngButton($remove_text1a, $remove_text2a)?>
                </a>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4">
                <label class=" text-sm-left"><small><?=$labels['date']?></small></label>
                <input type="text"
                       class="form-control form-control-sm datetimepicker"
                       name="operation[<?=$id?>][date]"
                       value="<?=$date_value?>"
                       maxlength="50">

            </div>
            <div class="col-md-5">
                <label class=" text-sm-left"><small><?=$labels['kind']?></small></label>
                <select style="box-sizing: border-box !important;" class="selectpicker"
                        name="operation[<?=$id?>][kind]"
                        id="operation[<?=$id?>][kind]"
                        data-db="kind"
                        data-width="100%"
                        data-style="btn-primary"
                        data-live-search="true"
                        title="..."
                >
                    <?php
                    foreach ($this->kinds as $kind):
                        $selected =
                            $operation->getKind()->getKindId() === $kind->getKindId() ? 'selected' : '';
                        echo '<option ' . $selected . ' class="form-control form-control-sm" '
                            . 'data-id="' . $kind->getKindId()
                            . '" data-name="' . $kind->getOperationKind()
                            . '" value="' . $kind->getKindId() . '">'
                            . $kind->getOperationKind() . '</option>';
                    endforeach;
                    ?>
                </select>

            </div>
            <div class="col-md-3">
                <a style="margin-top: 2rem; width: inherit"
                   href="javascript:void(0)"
                   onclick="reference('kind', this)"
                   class="btn btn-secondary">
                    <i class="fas fa-pen"></i> <?=$this->lngLabel('Typen', 'types')?>
                </a>
            </div>
            <div class="w-100"></div>
            <div class="col-md-5 offset-md-4">
                <label class=" text-sm-left"><small><?=$labels['surgeon']?></small></label>
                <select style="box-sizing: border-box !important;" class="selectpicker"
                        name="operation[<?=$id?>][surgeon]"
                        id="operation[<?=$id?>][surgeon]"
                        data-db="surgeon"
                        data-width="100%"
                        data-style="btn-primary"
                        data-live-search="true"
                        title="..."
                >
                    <?php
                    $current = $operation->getSurgeon() ? $operation->getSurgeon()->getSurgeonId() : null;
                    foreach ($this->surgeons as $surgeon):
                        $selected =
                            $current === $surgeon->getSurgeonId() ? 'selected' : '';
                        echo '<option ' . $selected . ' class="form-control form-control-sm" '
                            . 'data-id="' . $surgeon->getSurgeonId()
                            . '" data-name="' . $surgeon->getSurgeonName()
                            . '" value="' . $surgeon->getSurgeonId() . '">'
                            . $surgeon->getSurgeonName() . '</option>';
                    endforeach;
                    ?>
                </select>

            </div>
            <div class="col-md-3">
                <a style="margin-top: 2rem; width: inherit"
                   href="javascript:void(0)"
                   onclick="reference('surgeon', this)"
                   class="btn btn-secondary">
                    <i class="fas fa-pen"></i> Surgeons
                </a>
            </div>
            <div class="w-100"></div>
            <div class="col-md-4">
                <label class=" text-sm-left"><small><?=$labels['caseNumber']?></small></label>
                <input type="text"
                       class="form-control form-control-sm"
                       name="operation[<?=$id?>][caseNumber]"
                       value="<?=$this->escapeHtml($operation->getCaseNumber())?>"
                       maxlength="10">

            </div>
            <div class="col-md-5">
                <label class=" text-sm-left"><small><?=$labels['clinic']?></small></label>
                <select style="box-sizing: border-box !important;" class="selectpicker"
                       name="operation[<?=$id?>][clinic]"
                       id="operation[<?=$id?>][clinic]"
                        data-db="clinic"
                        data-width="100%"
                        data-style="btn-primary"
                        data-live-search="true"
                        title="..."
                >
                    <?php
                    $current = $operation->getClinic() ? $operation->getClinic()->getClinicId() : null;
                    foreach ($this->clinics as $clinic):
                        $selected =
                            $current === $clinic->getClinicId() ? 'selected' : '';
                        echo '<option ' . $selected . ' class="form-control form-control-sm" '
                            . 'data-id="' . $clinic->getClinicId()
                            . '" data-name="' . $clinic->getClinicName()
                            . '" value="' . $clinic->getClinicId() . '">'
                            . $clinic->getClinicName() . '</option>';
                    endforeach;
                    ?>
                </select>
            </div>
            <div class="col-md-3">
                <a style="margin-top: 2rem; width: inherit"
                   href="javascript:void(0)"
                   onclick="reference('clinic', this)"
                   class="btn btn-secondary">
                    <i class="fas fa-pen"></i> Clinics
                </a>
            </div>
            <div class="w-100"></div>
            <div class="col-md-6">
                <label class=" text-sm-left"><small><?=$labels['patientHeight']?></small></label>
                <input type="text"
                       class="form-control form-control-sm"
                       name="operation[<?=$id?>][patientHeight]"
                       value="<?=$operation->getPatientHeight()?>"
                >
            </div>
            <div class="col-md-6">
                <label class=" text-sm-left"><small><?=$labels['patientWeight']?></small></label>
                <input type="text"
                       class="form-control form-control-sm"
                       name="operation[<?=$id?>][patientWeight]"
                       value="<?=$operation->getPatientWeight()?>"
                >
            </div>
            <div class="w-100"></div>
            <div class="col-md-12">
                <label class=" text-sm-left"><small><?=$labels['remarks']?></small></label>
                <textarea
                       class="form-control form-control-sm"
                       name="operation[<?=$id?>][remarks]"
                       rows="3">
                    <?=$this->escapeHtml($operation->getRemarks())?>
                </textarea>
            </div>
            <div class="w-100"></div>
            <div class="col-md-12" id="operation_implants_<?=$id?>">
                <?php
                echo $this->partial('implant::list', ['implants' => $operation->getOperationImplant(), 'operation_id' => $id]);
                ?>
            </div>
            <div class="w-100"></div>
            <div class="col-md-12">
                <div class="operation-photo">
                </div>
            </div>
        </div>

    </td>
</tr>
