version: '2'

services:
  nginx:
      container_name: german-nginx
      image: nginx:latest
      ports:
          - 8017:80
      volumes:
          - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      volumes_from:
          - php
  php:
      container_name: german-php
      build: ./docker/php/
      expose:
          - 9000
      volumes:
          - .:/var/www/html
          - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      environment:
          PHP_IDE_CONFIG: serverName=mezzio-german
          PHP_XDEBUG_ENABLED: 1
          XDEBUG_CONFIG: remote_host=docker.for.mac.localhost
 
