<div class="row">
    <div class="col-sm-3">
        <a href="javascript:void(0)"
           class="btn btn-secondary"
           onclick="closeReference()">
            <i class="fas fa-times" aria-hidden="true"></i> <?=$this->lngButton('Schließen', 'close', true)?>
        </a>
    </div>
</div>
<br>

<?php
echo $this->lngLabel('Der von Ihnen ausgewählte Hersteller oder Typ wurde nicht gefunden',
    'The manufacturer or type you selected was not found', true);