<?php

$items=$this->items;
/** @var \App\Entity\Clinic $item */
$item=null;

?>

<option value="">...</option>
<?php foreach ($items as $item): ?>

    <?php
    $id = $item->getClinicId();
    $name = $this->escapeHtml($item->getClinicName());
    $address = $this->escapeHtml($item->getClinicAddress());
    $label = $name . ' ' . $address;
    ?>

    <option
            class="form-control"
            value="<?=$id?>"
            data-id="<?=$id?>"
            data-name="<?=$name?>"
            data-address="<?=$address?>">
        <?=$label?>
    </option>

<?php endforeach; ?>
