<?php
/** @var \App\Entity\Clinic[] $items */
$items = $this->items;

?>

<div class="h3">
    Reference <span class="small">clinics</span>
</div>
<span class="text-info"><?=$this->lngLabel('Um zu suchen, geben Sie 3 Zeichen ein', 'to search enter 3 characters')?></span>

<div class="row">
    <div class="col-sm-3">
        <a class="btn btn-primary" href="javascript:void(0);" onclick="editReference(event)"
           data-id="0"
           data-ref="clinic" data-name="" data-address="">
            <i class="fa fa-plus" aria-hidden="true"></i> <?=$this->lngLabel('Schaffen', 'create', true)?>
        </a>
    </div>
    <div class="col-sm-6">
        <input type="text" class="form-control"
               placeholder="filter"
               onkeyup="find(this)">
    </div>
    <div class="col-sm-3 pull-right">
        <a href="javascript:void(0)"
           class="btn btn-secondary float-right"
           onclick="closeReference('clinic')">
            <i class="fas fa-times" aria-hidden="true"></i> <?=$this->lngLabel('Schließen', 'close', true)?>
        </a>
    </div>
</div>
<br>

<div id="data-panel">
    <div class="list-group">
        <div class="list-group-item-heading">
            <div class="row">
                <div class="col-sm-6">
                    <?=$this->lngLabel('Name / Bezeichnung', 'Name / Designation')?>>
                </div>
            </div>
        </div>

        <?php foreach ($items as $item): ?>

            <?php
            echo $this->partial('reference::view-clinic', ['item'=>$item]);
            ?>

        <?php endforeach; ?>

    </div>
</div>

