<?php

/** @var \App\Entity\Kind $item */
$item = $this->item;
$id = $item->getKindId();
$name = $this->escapeHtml($item->getOperationKind());

$remove_text1 = 'Löschen operation ' . $name;
$remove_text2 = 'delete surgeon ' . $name;

?>

<div class="list-group-item delete-object" data-id="<?= $id ?>">
    <div class="row">
        <div class="col-sm-6 float-left">
            <a href="javascript:void(0)" onclick="editReference(event)"
               class="value-ref"
               data-id="<?=$id?>"
               data-name="<?=$name?>"
               data-ref="kind"
            >
                <?= $name ?>
            </a>
        </div>
        <div class="col-sm-2 float-right">
            <a href="javascript:void(0)"
               class="float-right text-danger"
               onclick="removeDocument('<?=$this->url('reference.delete',['item' => 'kind', 'id' => $id])?>', '<?=$remove_text1?>', '<?=$remove_text2?>', this)">
                <i class="fas fa-trash"></i>
            </a>

        </div>

    </div>
</div>
