<?php
$this->headTitle('ändere das Passwort');

$form->prepare();
?>

<div class="h3">
    Passwort ändern für <small class="text-primary h5"><?= $this->escapeHtml($user->getEmail()) ?></small>
</div>

<?= $this->form()->openTag($form); ?>
<div class="row">

    <div class="w-100"></div>
    <div class="form-group col-6">
        <label><?= $this->lngLabel('Neues Kennwort', 'new password')?></label>
        <?= $this->formElement($form->get('new_password')); ?>
        <?= $this->formElementErrors($form->get('new_password')); ?>
    </div>

    <div class="w-100"></div>
    <div class="form-group col-6">
        <label><?= $this->lngLabel('Kennwort bestätigen', 'confirm password')?></label>
        <?= $this->formElement($form->get('confirm_new_password')); ?>
        <?= $this->formElementErrors($form->get('confirm_new_password')); ?>
    </div>

    <?= $this->formElement($form->get('csrf')); ?>

    <div class="w-100 mt-4"></div>
    <div class="col-6">
        <button type="submit" class="btn btn-sm btn-success" >
            <i class="fa fa-key"></i> <?= $this->lngButton('Passwort ändern', 'Change password', true) ?>
        </button>
    </div>

    <?= $this->form()->closeTag(); ?>
</div>

