<?php
$action = $this->action;
$form = $this->form;
if ($action !== 'create') $head = 'Mitarbeiter';
else $head = 'Mitarbeitererstellung';

$this->headTitle($head);

$this->headLink()
    ->prependStylesheet("https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/css/bootstrap-select.min.css");
$this->inlineScript()
    ->prependFile("https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/js/bootstrap-select.min.js");
$this->inlineScript()->prependFile('/js/reference.js');
$this->inlineScript()->prependFile('/js/remove-window.js');


/** @var \App\Entity\User $user */
$user = $this->user;

/** @var User\Form\UserForm $form */
$form->get('email')->setAttributes([
    'class' => 'form-control form-control-sm',
    'placeholder' => 'name@example.com'
]);

$form->get('full_name')->setAttributes([
    'class' => 'form-control form-control-sm',
    'placeholder' => 'Mitarbeitername'
]);

$form->get('phoneOut')->setAttributes([
    'class' => 'form-control form-control-sm',
]);

$form->prepare();
?>
<div id="reference"></div>

<div id="patient">

<div class="h3">
    <?= $head ?>
    <small class="text-primary h5"><?= $this->escapeHtml($user->getFullName()) ?></small>
</div>

<?= $this->form()->openTag($form); ?>

<div class="row">

    <div class="form-group col-6">
        <label><?= $this->lngLabel('E-Mail', 'email'); ?></label>
        <?= $this->formElement($form->get('email')); ?>
        <?= $this->formElementErrors($form->get('email')); ?>
    </div>

    <div class="form-group col-6">
        <label><?= $this->lngLabel('Vollständiger Name', 'full name'); ?></label>
        <?= $this->formElement($form->get('full_name')); ?>
        <?= $this->formElementErrors($form->get('full_name')); ?>
    </div>

    <div class="w-100"></div>
    <div class="form-group col-6">
        <label><?= $this->lngLabel('Operateur', 'surgeon')?></label>
        <?= $this->formElement($form->get('surgeon')); ?>
        <?= $this->formElementErrors($form->get('surgeon')); ?>
    </div>

    <div class="col-3">
        <a style="margin-top: 2rem; width: inherit"
           href="javascript:void(0)"
           onclick="reference('surgeon', this)"
           class="btn btn-secondary">
            <i class="fas fa-pen"></i> <?= $this->lngLabel('Surgeons', '') ?>
        </a>
    </div>

    <div class="form-group col-6">
        <label><?= $this->lngLabel('Telefon', 'phone')?></label>
        <?= $this->formElement($form->get('phoneOut')); ?>
        <?= $this->formElementErrors($form->get('phoneOut')); ?>
    </div>

    <div class="w-100"></div>
    <?php if ($action === 'create'): ?>
        <div class="form-group col-6">
            <label><?= $this->lngLabel('Passwort', 'password')?></label>
            <?= $this->formElement($form->get('password')); ?>
            <?= $this->formElementErrors($form->get('password')); ?>
        </div>

        <div class="form-group col-6">
            <label><?= $this->lngLabel('Kennwort bestätigen', 'confirm password')?></label>
            <?= $this->formElement($form->get('confirm_password')); ?>
            <?= $this->formElementErrors($form->get('confirm_password')); ?>
        </div>
    <?php endif; ?>

    <div class="w-100"></div>
    <div class="form-group col-6">
        <label><?= $this->lngLabel('Rolle', 'role')?></label>
        <?= $this->formElement($form->get('role')); ?>
        <?= $this->formElementErrors($form->get('role')); ?>
    </div>
    <div class="col-6">
        <p class="text-muted mt-md-4" id="role_note"></p>
    </div>

    <div class="w-100"></div>
    <div class="form-group col-6">
        <label><?= $this->lngLabel('Status', '')?></label>
        <?= $this->formElement($form->get('status')); ?>
        <?= $this->formElementErrors($form->get('status')); ?>
    </div>
    <div class="col-6">
        <p class="text-muted mt-md-4" id="status_note"></p>
    </div>

    <?= $this->formElement($form->get('csrf')); ?>

    <div class="w-100 mt-4"></div>
    <div class="col-6">
        <button class="btn btn-sm btn-success" type="submit">
            <i class="far fa-save"></i> <?= $this->lngButton('Sparen', 'save', true) ?>
        </button>
    </div>
    <div class="col-6">
        <?php if ($action !== 'create'): ?>
        <a class="btn btn-sm btn-secondary" href="<?= $this->url('user.change-password',
            ['id' => $user->getUserId()]); ?>">
            <i class="fa fa-key"></i> <?= $this->lngButton('Passwort ändern', 'Change password', true) ?>
        </a>
        <?php endif; ?>
    </div>

</div>

<?= $this->form()->closeTag(); ?>


</div>

<?php
$this->inlineScript()->captureStart();
echo <<<JS

    $(function () {
        $('.input-error').addClass('is-invalid');

        $('select[name="role"]').trigger('onchange');
        $('select[name="status"]').trigger('onchange');
    });
    function changeRole(element) {
        let opt=$(element).find('option:selected');
        $('#role_note').html(opt.data('note'));
    }
    function changeStatus(element) {
        let opt=$(element).find('option:selected');
        let res= 'closed';
        if (opt.val() === '1') res = 'active';
        $('#status_note').html(res);
    }

JS;
$this->inlineScript()->captureEnd();
?>
