<?php
$this->headTitle('Сброс пароля');
?>

<div class="row">
    <div class="col-md-offset-4 col-md-5">
        <h1>Сброс пароля</h1>

        <?php if ($id=='sent'): ?>
            <p>
                Ссылка для сброса пароля отправлена на Ваш адрес эл-почты.
            </p>
        <?php elseif ($id=='invalid-email'): ?>
            <p>
                Не найден пользователь с таким адресом эл-почты.
            </p>
        <?php elseif ($id=='set'): ?>
            <p>
                Новый пароль был успешно установлен.
            </p>
            <p>
                Выполнить <a href="<?= $this->url('login'); ?>">Вход</a>.
            </p>
        <?php elseif ($id=='failed'): ?>
            <p>
            Неверный ключ сброса или время операции истекло. Пожалуйста нажмите
            <a href="<?= $this->url('user.reset-password') ?>">здесь</a> и попробуйте выполнить сброс пароля снова.
            </p>
        <?php endif; ?>
    </div>
</div>