<ul class="navbar-nav mr-auto">
    <?php foreach ($this->container as $page):?>
        <?php if ($this->navigation()->accept($page)):?>
            <li class="nav-item">
                <?php
                if ($page->get('out_href')):
                    $href = $page->get('out_href');
                else:
                    $href= $page->getHref();
                endif;
                ?>
                <a href="<?=$href?>" class="nav-link" target="<?=$page->getTarget()?>">
                    <?=$page->getTitle()?> <?=$page->getLabel()?>
                </a>
            </li>
        <?php endif;?>
    <?php endforeach;?>
</ul>
