<ul class="navbar-nav mr-auto">
    <?php /** @var \App\Navigation\ExpressiveNavigationPage $page */
    foreach ($this->container as $page):?>
        <?php if ($this->navigation()->accept($page)):?>
            <li class="nav-item">
                <?php
                if ($page->get('out_href')):
                    $href = $page->get('out_href');
                else:
                    $href= $page->getHref();
                endif;
                ?>
                <a href="<?=$href?>" class="nav-link" target="<?=$page->getTarget()?>">
                    <?=$page->getTitle()?> <?=$page->getLabel()?>
                    <br>
                    <span class="english-label">
                        <?=$page->getCustomProperties()['english'] ?? '';?>
                    </span>
                </a>
            </li>
        <?php endif;?>
    <?php endforeach;?>
</ul>
