<?php
$this->headLink()
    ->prependStylesheet('https://use.fontawesome.com/releases/v5.13.0/css/all.css')
    ->prependStylesheet('/css/flatly.bootstrap.min.css');
$this->inlineScript()
    ->prependFile('/js/bootstrap.bundle.min.js')
    ->prependFile('https://code.jquery.com/jquery-3.5.1.min.js');
?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <link rel="shortcut icon" href="/img/favicon.ico" />
    <?=$this->headTitle('SomeApp')->setSeparator(' - ')->setAutoEscape(false)?>
    <?=$this->headMeta()?>
    <?=$this->headLink()?>
    <style>
        body { padding-top: 70px; }
        .app { min-height: 100vh; }
        .navbar-brand img { margin: -.5rem 0; filter: brightness(0) invert(1); }
        label { margin-top: 1rem; }
    </style>
</head>
<body class="app">

    <div class="app-content">
        <main class="container">
            <?=$this->flash()?>
            <?=$this->content?>
        </main>
    </div>

    <?php echo $this->inlineScript(); ?>
</body>
</html>
