<?php

$this->login_form->get('csrf')->setValue($this->token);
//$this->login_form->prepare();
//echo $this->form($this->login_form);

$this->headTitle('Eingang');


$this->login_form->get('username')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'e-mail',
    'required' => true,
    'autofocus' => true
])
    ->setLabelAttributes([
        'class' => 'sr-only'
    ]);

$this->login_form->get('password')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'password',
    'required' => true,
])
    ->setLabelAttributes([
        'class' => 'sr-only'
    ]);
?>

    <div class="">
        <form style="margin: auto;max-width: 330px;padding: 15px;width: 100%" method="post">
<!--            <h1 class="h3 mb-3">Login</h1>-->
<!--            --><?php //if ($isLoginError): ?>
<!--                <div class="alert alert-warning" role="alert">-->
<!--                    Неверные данные для входа.-->
<!--                </div>-->
<!--            --><?php //endif; ?>
            <label><?=$this->lngLabel('Nutzername', 'username')?></label>
            <?= $this->formElement($this->login_form->get('username')); ?>

            <label><?=$this->lngLabel('Passwort', 'password')?></label>
            <?= $this->formElement($this->login_form->get('password')); ?>

            <?= $this->formElement($this->login_form->get('redirect_url')); ?>
            <?= $this->formElement($this->login_form->get('csrf')) ?>

            <button class="btn btn-lg btn-primary btn-block mt-4" type="submit">Login</button>
        </form>
    </div>
